"""Schema-safe defaults for fail-closed rollback and smoke stubs (v19.0.4+)."""
from __future__ import annotations

import copy
import functools
import json
from pathlib import Path
from typing import Any, Mapping

from runtime.schema_synth import synth_from_json_schema as _synth_from_schema
from runtime.util import now

ZERO64 = "0" * 64

_SCHEMAS_DIR = Path(__file__).resolve().parent.parent / "schemas" / "core"

# Whitelist: only these logical names may be synthesized by minimal_valid().
_EMERGENCY_DEFAULTS: dict[str, dict[str, Any]] = {
    "delivery-manifest": {
        "schema_version": "v19.0",
        "run_id": "__minimal__",
        "delivery_status": "validation_failed",
        "attachments": [],
        "local_paths_exposed": False,
        "artifact_ready_claim_allowed": False,
        "external_delivery_claim_allowed": False,
        "stub_delivery_disclosure_required": True,
        "provider_capability_snapshot": {},
        "real_external_delivery": False,
        "stub_delivery": True,
        "created_at": now(),
    },
    "final-answer-gate": {
        "schema_version": "v19.0",
        "run_id": "__minimal__",
        "passed": False,
        "status": "fail",
        "checks": {},
        "contradiction_echo": {
            "contradiction_level": 0,
            "contradiction_scan_performed": False,
            "scan_scope": "none",
            "high_severity_detected": False,
        },
        "overconfidence_risk": {"blocking": [], "warnings": [], "signals": {}},
        "created_at": now(),
    },
    "runtime-status": {
        "run_id": "__minimal__",
        "job_id": "",
        "command_id": "",
        "state": "validation_failed",
    },
}

ROLLBACK_STUB_HTML = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>Rollback stub</title>
<meta name="rollback-marker" content="rfo-v19-fail-closed-rollback"></head>
<body><h1>Rollback stub</h1>
<p>Generated by <code>_fail_closed_rollback</code> after validation failure.</p>
</body></html>
"""


@functools.cache
def _load_schema(schema_name: str) -> dict[str, Any] | None:
    path = _SCHEMAS_DIR / f"{schema_name}.schema.json"
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


# JSON Schema synthesis lives in ``runtime.schema_synth`` (single implementation).


def minimal_valid(schema_name: str, overrides: Mapping[str, Any] | None = None) -> dict[str, Any]:
    """Return a minimal object valid under v19 core schemas for rollback / worker bootstrap.

    ``schema_name`` is a basename key (e.g. ``delivery-manifest``), not a filesystem path.
    Unknown names raise ``RuntimeError`` (fail-closed).
    """
    if schema_name not in _EMERGENCY_DEFAULTS:
        raise RuntimeError(
            f"minimal_valid: unknown schema_name={schema_name!r}; add to _EMERGENCY_DEFAULTS whitelist"
        )
    schema = _load_schema(schema_name)
    base = copy.deepcopy(_EMERGENCY_DEFAULTS[schema_name])
    if schema is not None:
        try:
            synth = _synth_from_schema(schema)
            if isinstance(synth, dict):
                for k, v in synth.items():
                    if k not in base or base[k] in (None, "", [], {}):
                        base[k] = v
        except Exception:
            pass
    if overrides:
        base.update(dict(overrides))
    if "created_at" in base and not base.get("created_at"):
        base["created_at"] = now()
    return base


def merge_rollback_delivery_manifest(dm: dict[str, Any]) -> dict[str, Any]:
    """Return a copy of delivery-manifest with validation-failed rollback fields (schema-safe)."""
    out: dict[str, Any] = dict(dm)
    out.update(
        {
            "delivery_status": "validation_failed",
            "real_external_delivery": False,
            "artifact_ready_claim_allowed": False,
            "external_delivery_claim_allowed": False,
            "stub_delivery": True,
            "stub_delivery_disclosure_required": True,
            "publish_allowed": False,
            "publish_reason": "validation_failed",
            "updated_at": now(),
        }
    )
    atts = out.get("attachments")
    if not isinstance(atts, list) or len(atts) == 0:
        out["attachments"] = [{"path": "report/rollback-stub.html", "sha256": ZERO64}]
    return out


def merge_rollback_final_answer_gate(fg: dict[str, Any]) -> dict[str, Any]:
    out: dict[str, Any] = dict(fg)
    out.update({"passed": False, "status": "fail", "updated_at": now()})
    return out
